### ISSUE TITLE
Link to AUR package is dead

### ISSUE THREAD

**Issue by MisterDA** [rdnetto/YCM-Generator#100]
Hello, the link to the Arch Linux AUR package is dead.
The new link is https://aur.archlinux.org/packages/ycm-generator-git.

Could you tell the name of the package directly?

```
[AUR package](https://aur4.archlinux.org/packages/ycm-generator-git/).
[ycm-generator-git]([AUR package](https://aur4.archlinux.org/packages/ycm-generator-git/)
```

What do you mean by "(unofficial)"? Is the package unofficial relatively to Arch Linux because it's in the AUR, or relatively to YCM-Generator because it (maybe) not maintained by a ycm-generator contributor (which I haven't checked)?

Thanks.

**Comment by ssfdust** [comment]
Please check the development branch.

2017年3月29日 下午9:52，"Antonin Décimo" <notifications@github.com>写道：
