### ISSUE TITLE
ERROR: No commands were logged to the build logs 

### ISSUE THREAD

**Issue by xinquanatcolezhu** [rdnetto/YCM-Generator#107]
I am having this issue problem and could not figure out why

my cmake json file looks like this
cat compile_commands.json 
` 
[
{
  "directory": "/Users/xinquan/Dropbox/source-code/cmake-pj/oms/build",
  "command": "/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++   -I/Users/xinquan/Dropbox/source-code/cmake-pj/oms/build/ext/include   -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk   -std=c++14 -Wall -o CMakeFiles/oms.dir/src/OrderState.cpp.o -c /Users/xinquan/Dropbox/source-code/cmake-pj/oms/src/OrderState.cpp",
  "file": "/Users/xinquan/Dropbox/source-code/cmake-pj/oms/src/OrderState.cpp"
},
{
  "directory": "/Users/xinquan/Dropbox/source-code/cmake-pj/oms/build",
  "command": "/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++   -I/Users/xinquan/Dropbox/source-code/cmake-pj/oms/build/ext/include   -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk   -std=c++14 -Wall -o CMakeFiles/oms.dir/src/main.cpp.o -c /Users/xinquan/Dropbox/source-code/cmake-pj/oms/src/main.cpp",
  "file": "/Users/xinquan/Dropbox/source-code/cmake-pj/oms/src/main.cpp"
`

xinquan@:~/Dropbox/source-code/cmake-pj/oms/build$ ~/projects/external/YCM-Generator/config_gen.py . --verbose
Preparing build directory...
$ make clean

Running make...
$ make -i -j4
[  9%] Creating directories for 'bitsx-lib'
[ 18%] Performing download step (DIR copy) for 'bitsx-lib'
[ 36%] No patch step for 'bitsx-lib'
[ 36%] No update step for 'bitsx-lib'
[ 45%] Performing configure step for 'bitsx-lib'
-- Configuring done
-- Generating done
-- Build files have been written to: /Users/xinquan/Dropbox/source-code/cmake-pj/oms/build/ext/src/bitsx-lib-build
[ 54%] Performing build step for 'bitsx-lib'
Scanning dependencies of target bitsx
[ 50%] Building CXX object CMakeFiles/bitsx.dir/BoardSessionConfig.cpp.o
[100%] Linking CXX static library libbitsx.a
[100%] Built target bitsx
[ 63%] Performing install step for 'bitsx-lib'
[100%] Built target bitsx
Install the project...
-- Install configuration: ""
-- Installing: /Users/xinquan/Dropbox/source-code/cmake-pj/oms/build/ext/lib/libbitsx.a
-- Installing: /Users/xinquan/Dropbox/source-code/cmake-pj/oms/build/ext/include/bitsx/BoardSessionConfig.h
-- Installing: /Users/xinquan/Dropbox/source-code/cmake-pj/oms/build/ext/include/bitsx/MaxTypes.h
[ 72%] Completed 'bitsx-lib'
[ 72%] Built target bitsx-lib
Scanning dependencies of target oms
[ 81%] Building CXX object CMakeFiles/oms.dir/src/OrderState.cpp.o
[ 90%] Building CXX object CMakeFiles/oms.dir/src/main.cpp.o
[100%] Linking CXX executable oms
[100%] Built target oms
Build completed in 2.11 sec

Collected 0 relevant entries for C compilation (0 discarded).
Collected 0 relevant entries for C++ compilation (0 discarded).

ERROR: No commands were logged to the build logs (C: /var/folders/nl/gf1zldh16xb32t9tpbhxpbp40000gn/T/tmp2OzUuV, C++: /var/folders/nl/gf1zldh16xb32t9tpbhxpbp40000gn/T/tmpu0qs33).
Your build system may not be compatible.

**Comment by xyz1001** [comment]
I have the same problem

> Running cmake in '/tmp/tmpSzBSfW'...
> $ cmake /home/xxx/Project/xxx/xxx
> -- The C compiler identification is Clang 5.0.1
> -- The CXX compiler identification is Clang 5.0.1
> -- Check for working C compiler: /usr/bin/clang
> -- Check for working C compiler: /usr/bin/clang -- works
> -- Detecting C compiler ABI info
> -- Detecting C compiler ABI info - done
> -- Detecting C compile features
> -- Detecting C compile features - done
> -- Check for working CXX compiler: /usr/bin/clang++
> -- Check for working CXX compiler: /usr/bin/clang++ -- works
> -- Detecting CXX compiler ABI info
> -- Detecting CXX compiler ABI info - done
> -- Detecting CXX compile features
> -- Detecting CXX compile features - done
> -- Configuring done
> -- Generating done
> -- Build files have been written to: /tmp/tmpSzBSfW
> 
> Running make...
> $ make -i -j4
> Scanning dependencies of target helloworld_service
> Scanning dependencies of target crcp
> [  5%] Building CXX object helloworld_service/CMakeFiles/helloworld_service.dir/boost_system_header_only.cpp.o
> ...
> [100%] Linking CXX executable xxx
> [100%] Built target xxx
> 
> Cleaning up...
> 
> Build completed in 14.16 sec
> 
> Collected 0 relevant entries for C compilation (0 discarded).
> Collected 0 relevant entries for C++ compilation (0 discarded).
> 
> ERROR: No commands were logged to the build logs (C: /tmp/tmp8DG1vs, C++: /tmp/tmpi1KX6G).
> Your build system may not be compatible.
> 
> Shell 已返回3
>
