### ISSUE TITLE
meson support not working with ccache: Unknown compiler(s): [['clang']]

### ISSUE THREAD

**Issue by gdesmott** [rdnetto/YCM-Generator#111]
I'm not able to use meson support with current develop branch (9cb722aa4e6247a17b8e8603f471bbc9b283bc0c).
Here is the output with nautilus (used as testing according to README).

```
Configuring meson in '/tmp/tmpag33nO'...
('\nRunning meson...', '/home/cassidy/tmp/nautilus')
$ meson /home/cassidy/tmp/nautilus
Warning: You are using 'ANSI_X3.4-1968' which is not a Unicode-compatible locale.
You might see errors if you use UTF-8 strings as filenames, as strings, or as file contents.
Please switch to a UTF-8 locale for your platform.
The Meson build system
Version: 0.43.0
Source dir: /home/cassidy/tmp/nautilus
Build dir: /tmp/tmpag33nO
Build type: native build
Project name: nautilus

Meson encountered an error in file meson.build, line 1, column 0:
Unknown compiler(s): [['clang']]
```

I tried with meson 0.41.2 and 0.43.0.
I do have clang and clang++ installed.

@vyasgiridhar : am I missing something here?

**Comment by vyasgiridhar** [comment]
I am not able to reproduce the issue on a fresh clone of Nautilus. Also, YCM-Generator doesn't use the systems build tools. It uses it's own build tools binary that returns true for all executions AFAIK.

The 'c' in project declaration in meson.build is the language the project is written in.
The only way to use clang is by setting 
```
CC=clang CXX=clang++ meson nautilus/
```
I am not so sure about the string encoding error though. 
 Hope that helps :grinning:

**Comment by gdesmott** [comment]
Manually launching `meson` with clang is working.
Looks like the problem is `ccache` going in the way (Fedora 25). If I remove it it does find it in the `config_gen.py` script. So I guess the `clang` from the fake toolchain isn't propery hooked or something.

**Comment by rdnetto** [comment]
Using YCM-Gen with ccache is unsupported and unlikely to work. As noted above, YCM-Gen works by compiling the project with a fake/no-op toolchain which records the compiler flags. If ccache is interfering with this, then the flags we collect are likely to be incomplete/missing.

You'll need to disable ccache when using YCM-Gen on that project to workaround this.
