### ISSUE TITLE
ESP32 IDF and YCM-Generator not working well together

### ISSUE THREAD

**Issue by mcgdb** [rdnetto/YCM-Generator#127]
I'm running into a problem with the esp-idf from Espressif for ESP32.
I've pushed the project here:  [repo](https://github.com/dale6998/spi_master)
I'm running Arch, and it's on python3, but all the Espressif python scripts that are called during the build process are python2.  There's an ncurses tool that you can call with `make menuconfig` so that you can change this, but I don't know how to make change known to YCM-Generator, so I changed the shebang to the right python2 path in the `esptool_py` file, which helped me get a little further.

However, I'm still seeing this:

```
[100%] Generating ../spi_master.bin
esptool.py v2.6
[100%] Built target app
$ make -i -j4

Cleaning up...

Build completed in 43.57 sec

Collected 0 relevant entries for C compilation (0 discarded).
Collected 0 relevant entries for C++ compilation (0 discarded).

ERROR: No commands were logged to the build logs (C: /tmp/tmpuv9ak61l, C++: /tmp/tmp58_m2w17).
Your build system may not be compatible.
```

Here's CMakeLists.txt file
```
# The following lines of boilerplate have to be in your project's CMakeLists
# in this exact order for cmake to work correctly
cmake_minimum_required(VERSION 3.5)

include($ENV{IDF_PATH}/tools/cmake/project.cmake)
project(spi_master)
```
Here's the Makefile
```
#
# This is a project Makefile. It is assumed the directory this Makefile resides in is a
# project subdirectory.
#

PROJECT_NAME := spi_master

include $(IDF_PATH)/make/project.mk

```
Here's how I'm trying to invoke YCM-Generator:
`user@bubbles:~/esp/spi_master(master⚡) » ycm_generator . --verbose --preserve-environment`

This build system is a little over my head...I'm used to just having a single Makefile and GCC, so I could use any advice or help you've got!  Thanks!

**Comment by rdnetto** [comment]
My guess is your build system hardcodes the name of the compiler, instead of using `CC` or `gcc`. If you can determine that name of the compiler it's using, you can add a symlink for it under `fake-toolchain/Unix`.

(Note that if it hardcodes the entire *path* to the compiler, then it's not possible to use YCM-Gen with it.)

**Comment by mcgdb** [comment]
Alright, thanks!  I'm looking around here, and I see that the name of the compiler is `xtensa-esp32-elf-gcc` and that it's in `~/esp/extensa-esp32-elf/bin/`.
I'm not sure where to look in the project files to determine the first part of your response (is it hardcoded)...Where should I see evidence of that?

And, can you describe in more detail how to symlink our way out of this?  Thanks!

**Comment by rdnetto** [comment]
> I'm not sure where to look in the project files to determine the first part of your response (is it hardcoded)...Where should I see evidence of that?

That would be specific to your build system, which I'm completely unfamiliar with.

> And, can you describe in more detail how to symlink our way out of this? Thanks!

When YCM-Gen generates the configuration, it does so by "building" the project with `YCM-Generator/fake-toolchain/Unix` in `PATH`. The files in that directory are just symlinks to one of two scripts, which record the flags they're invoked with for analysis by YCM-Gen. Therefore, you should be able to get it working by running the following command in that directory:

```
cp -a gcc xtensa-esp32-elf-gcc
```

(Note you might need to do something similar for the linker)

**Comment by mcgdb** [comment]
Ok, I've done what you suggested.  Here's what the `Unix` directory looks like after `cp- a gcc xtensa-esp32-elf-gcc; cp -a ld xtensa-esp32-elf-ld`

```
dale@bubbles:~/esp/spi_master(master⚡) » ll /usr/share/YCM-Generator/fake-toolchain/Unix 
total 12K
lrwxrwxrwx 1 root root   4 Dec 30 21:37 ar -> true
lrwxrwxrwx 1 root root   3 Dec 30 21:37 arm-none-eabi-g++ -> cxx
lrwxrwxrwx 1 root root   2 Dec 30 21:37 arm-none-eabi-gcc -> cc
lrwxrwxrwx 1 root root   4 Dec 30 21:37 as -> true
lrwxrwxrwx 1 root root   3 Dec 30 21:37 avr-g++ -> cxx
lrwxrwxrwx 1 root root   2 Dec 30 21:37 avr-gcc -> cc
-rwxr-xr-x 1 root root 424 Dec 30 21:37 cc
lrwxrwxrwx 1 root root   2 Dec 30 21:37 clang -> cc
lrwxrwxrwx 1 root root   3 Dec 30 21:37 clang++ -> cxx
-rwxr-xr-x 1 root root 427 Dec 30 21:37 cxx
lrwxrwxrwx 1 root root   3 Dec 30 21:37 g++ -> cxx
lrwxrwxrwx 1 root root   2 Dec 30 21:37 gcc -> cc
lrwxrwxrwx 1 root root   3 Dec 30 21:37 gcc++ -> cxx
lrwxrwxrwx 1 root root   4 Dec 30 21:37 ld -> true
lrwxrwxrwx 1 root root   4 Dec 30 21:37 nm -> true
-rwxr-xr-x 1 root root 116 Dec 30 21:37 true
lrwxrwxrwx 1 root root   2 Dec 30 21:37 xtensa-esp32-elf-gcc -> cc
lrwxrwxrwx 1 root root   4 Dec 30 21:37 xtensa-esp32-elf-ld -> true
```

And here's the output of YCM-Generator now:
```
dale@bubbles:~/esp/spi_master(master○) » ycm_generator . --verbose --preserve-environment >> output
CMake Error at /usr/share/cmake-3.13/Modules/CMakeTestCCompiler.cmake:52 (message):
  The C compiler

    "/usr/share/YCM-Generator/fake-toolchain/Unix/xtensa-esp32-elf-gcc"

  is not able to compile a simple test program.

  It fails with the following output:

    Change Dir: /tmp/tmpqwnzff0w/CMakeFiles/CMakeTmp
    
    Run Build Command:"/usr/bin/make" "cmTC_a0cc4/fast"
    /usr/bin/make -f CMakeFiles/cmTC_a0cc4.dir/build.make CMakeFiles/cmTC_a0cc4.dir/build
    make[1]: Entering directory '/tmp/tmpqwnzff0w/CMakeFiles/CMakeTmp'
    Building C object CMakeFiles/cmTC_a0cc4.dir/testCCompiler.c.obj
    /usr/share/YCM-Generator/fake-toolchain/Unix/xtensa-esp32-elf-gcc   -mlongcalls    -o CMakeFiles/cmTC_a0cc4.dir/testCCompiler.c.obj   -c /tmp/tmpqwnzff0w/CMakeFiles/CMakeTmp/testCCompiler.c
    clang-7: error: unknown argument '-mlongcalls', did you mean '-mlong-calls'?
    make[1]: *** [CMakeFiles/cmTC_a0cc4.dir/build.make:66: CMakeFiles/cmTC_a0cc4.dir/testCCompiler.c.obj] Error 1
    make[1]: Leaving directory '/tmp/tmpqwnzff0w/CMakeFiles/CMakeTmp'
    make: *** [Makefile:121: cmTC_a0cc4/fast] Error 2
    

  

  CMake will not be able to correctly generate this project.
Call Stack (most recent call first):
  /home/dale/esp/esp-idf/tools/cmake/project.cmake:86 (__project)
  CMakeLists.txt:6 (project)


make: *** No targets specified and no makefile found.  Stop.
```

I've also verified that those `xtensa-esp32-elf-gcc` and `xtensa-esp32-elf-ld` files are in fact in my `$PATH`.

**Comment by mcgdb** [comment]
Fixed it by doing what you've alluded to in other issues with similar problems.  For those who need it spelled out for them (like me :) ), here's what I did that made it work:

```
$> cd ~/.vim/bundle/YCM-Generator/fake-toolchain/Unix
$> ln -s cc xtensa-esp32-elf-gcc
```

Then, in the project root, the following will work:
```
~/.vim/bundle/YCM-Generator/config_gen.py -c $(which xtensa-esp32-elf-gcc) --verbose --preserve-environment .

```
