### ISSUE TITLE
package request.

### ISSUE THREAD

**Issue by ssfdust** [rdnetto/YCM-Generator#15]
hello,
I want to pack this git repo and upload to aur(archlinux user repository).may I?
ssfdust

**Comment by rdnetto** [comment]
Sure, no problem. Just let me know when you're done so I can update the README with the package name. :)

**Comment by ssfdust** [comment]
The package name is ycm-generator-git.The aur page is located at https://aur4.archlinux.org/packages/ycm-generator-git/.
And I make a little change to plugin/ycm-generator.vim, moving the script to /usr/share/vim/vimfiles/plugin and modifying the config_gen variable.
Becasue aur is updating recently, it can't be installed via a simple command. :(
But I think this will be supported soon.

**Comment by rdnetto** [comment]
Great, thanks for your work.
