### ISSUE TITLE
Needs to clear CMake cache before running

### ISSUE THREAD

**Issue by Unarelith** [rdnetto/YCM-Generator#16]
Before clearing CMake cache, I had this problem:

```
$ cmake /home/linux/Projects/ZeldaOOL
-- The C compiler identification is unknown
-- The CXX compiler identification is unknown
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- broken
CMake Error at /usr/share/cmake-3.2/Modules/CMakeTestCCompiler.cmake:61 (message):
  The C compiler "/usr/bin/cc" is not able to compile a simple test program.
```

Now it seems to be ok. I think it's because I use GCC with CMake, and the fake build uses Clang?

Maybe add a line in `README.md` to tell users a clear is needed?

**Comment by rdnetto** [comment]
That's odd - cmake is run out-of-tree, so it shouldn't make any changes to the project dir at all.
Can you please provide me with step-by-step instructions on how to reproduce this?
Also, can you see if it can be reproduced with [this project](https://github.com/clementine-player/Clementine.git) (this is the 'official' test case for the cmake code), or only with the one you were using?

**Comment by Unarelith** [comment]
Sure, my project is here: [https://github.com/Quent42340/ZeldaOOL](https://github.com/Quent42340/ZeldaOOL)

Steps to reproduce:
- Compile the project once with g++ following `README.md` instructions
- Open a file in the root of the project tree with vim
- Run `:CCGenerateConfig --verbose`

I'll try to reproduce the issue with Clementine, I'll let you know

**Comment by rdnetto** [comment]
Important detail: are you compiling in-tree or out-of-tree?

**Comment by Unarelith** [comment]
I'm compiling in-tree

**Comment by rdnetto** [comment]
Ah, that explains it - I had assumed cmake builds were being performed out-of-tree.

It looks like simply deleting `CMakeCache.txt` is enough to force cmake to generate a new build system, although as users can make changes to it deleting it outright would be a bad idea. I'll add some code to temporarily move it out of tree while the flags are being collected.

**Comment by rdnetto** [comment]
Can you confirm that that patch fixes the issue? (You'll need to checkout the `develop` branch.)

**Comment by Unarelith** [comment]
I tried with `:CCGenerateConfig` and it seems to be ok now, thanks

**Comment by rdnetto** [comment]
Great, no problem.
