### ISSUE TITLE
Add -e to make_args

### ISSUE THREAD

**Issue by hcgraf** [rdnetto/YCM-Generator#2]
Hi,

please add the switch -e / --environment-overrides to your make_args.
This allows overriding CC, CXX even if they are unconditionally assigned with '=' inside the Makefile.
It should not have any negative side-effects.

Thanks for your work!
Hagen Graf

**Comment by rdnetto** [comment]
The problem with enabling -e is that it will break any makefile that attempts to modify a variable overridden by the environment.

What I'll do instead is add a flag to enable the user to specify the flags to be passed to make - that way the default case is unchanged, but you can override this as necessary.

**Comment by rdnetto** [comment]
Can you checkout the develop branch and verify this works as desired?

**Comment by hcgraf** [comment]
Thanks for your effort! I'm currently not at a computer, but I'll try it asap!
Regards,
Hagen

Am 4. April 2015 10:28:57 MESZ, schrieb rdnetto <notifications@github.com>:

**Comment by hcgraf** [comment]
Another quick idea:
Using "make CC=..." instead of "CC=... make" should override Makefile settings for CC.

Am 4. April 2015 10:28:57 MESZ, schrieb rdnetto <notifications@github.com>:

**Comment by rdnetto** [comment]
No problem.

>Another quick idea:
>Using "make CC=..." instead of "CC=... make" should override Makefile settings for CC.


Passing CC=.. via --make-flags should work as well then. It still suffers from the problem of preventing the Makefile from modifying the variables though, so I can't make it the default.

**Comment by hcgraf** [comment]
I'm sorry it took a bit longer…
Now I was able to checkout develop and give it a try. It works, but it's a little bit cumbersome to remember using ":YCMGeneraterConfig -M=-e" using the vim-plugin.
To be honest, I don't quite understand how a Makefile could want to override CC, CXX without breaking your config-generation, as your code relies on clang being used.

Anyway, it usually works, and if it doesn't, I know what to look for ;)
So thanks a lot!

**Comment by rdnetto** [comment]
> To be honest, I don't quite understand how a Makefile could want to override CC, CXX without breaking your config-generation, as your code relies on clang being used.

Wrapper scripts. A good example is OpenMPI, which has a script called mpicc that calls the actual compiler with some extra options. I'm not aware of any specific cases where the makefiles work by overriding CC, but it seems quite likely they exist.

> It works, but it's a little bit cumbersome to remember using ":YCMGeneraterConfig -M=-e" using the vim-plugin.
You may way to define a command in your vimrc as an alias for that. :P
