### ISSUE TITLE
Fails when clang path contains "clang"

### ISSUE THREAD

**Issue by bartlibert** [rdnetto/YCM-Generator#21]
My version of clang is installed in path that contains "clang" in its name, i.e. ~/build/share/clang/trunk/bin/clang.
This tools fails because to determine the path of the c++ compiler, it replaces "clang" with "clang++", leading to:
ERROR: Could not find clang++ at '<my home>/build/share/clang++/trunk/bin/clang++'. Please make sure it is installed and specified appropriately
I temporarily fixed it locally by using
cxx = os.path.join(os.path.dirname(args["compiler"]), 'clang++') or 'clang++'
but you might prefer an other/better solution.

**Comment by rdnetto** [comment]
I just pushed a fixed version. Can you please check it out and verify if this fixes the problem?

**Comment by bartlibert** [comment]
I can confirm this fixes the issue, thanks!

(Apologies for the late reply, I was abroad with very limited internet access)
