### ISSUE TITLE
deal with cd during build

### ISSUE THREAD

**Issue by proudzhu** [rdnetto/YCM-Generator#22]
Some projects may change directory during build, is it possible to deal with such situation.
For example, https://github.com/xiph/speexdsp, ycm_generator will generate flags like '-I../include' as it change directory to libspeexdsp during build, but it should be '-I./include'.

**Comment by rdnetto** [comment]
This is going to be slightly tricky - it means that the working directory needs to be logged, and that `-I` needs to have special treatment to resolve relative paths appropriately.

It's also worth noting this only appears to affect a minority of autotools projects (AFAICT), and that a partial workaround is to use `--out-of-tree`.

This is a fairly minor bug (it's easy enough to fix the generated flags) that only affects a few projects, so it'll have a fairly low priority. I'll try and get around to it at some point, but as I'm going to be quite busy over the next week or two I can't make any guarantees.

**Comment by proudzhu** [comment]
Thanks, --out-of-tree works
