### ISSUE TITLE
env entry for HOME

### ISSUE THREAD

**Issue by laxitg** [rdnetto/YCM-Generator#26]
Hi,

First of all thanks for taking the effort to automate config files for YCM. Although i think i have a possible enhancement.

find_package command in cmake searches for the package config file in couple of directories, one of the directories is `$HOME/.cmake/packages/<package>/`. A file with random name in the aforementioned directories points to the location of config file. This happens when the package we are looking for uses the `export(PACKAGE)` and doesn't provide `install` option. Unfortunately i was using such packages.

cmake in all cases was working, but YCM-Generator was failing for packages in User package registry, reason being `env` passed to `run` was not containing entry for `HOME`. I know one can use the preserve_environment for such cases, but having HOME in for the default case could be benficial all around.

**Comment by rdnetto** [comment]
So, I've thought about this a bit, and the goal of not preserving the environment by default is to minimize the likelihood of some temporary variable (e.g. a change to `PATH`) modifying the behaviour of the compilation process, especially as YCM will be run with Vim's environment (which will lack changes made in your shell's .rc file if running as vim-qt, etc.).

`HOME` isn't likely to change unless multiple users are involved and the project is stored on a shared drive/path, but that's a pretty niche case, so I might as well make life easier for the majority of users and hope this doesn't turn out to have some far-reaching consequences I didn't anticipate. :package: 

(I've pushed the commit to the `develop` branch - please test this and let me know if it doesn't solve your problem.)

Sorry about the delay in replying, I just moved interstate and have had my plate full til now.
