### ISSUE TITLE
Does not work with LLVM tree

### ISSUE THREAD

**Issue by artagnon** [rdnetto/YCM-Generator#28]
Clone llvm.git and run ycm-gen on it -- fails. The verbose output is too large to include here; please run yourself.

**Comment by rdnetto** [comment]
For future reference, when reporting bugs against specific projects please include a link to the repo/tarball and the branch / version number. (For my own reference, it's [here](http://llvm.org/git/llvm.git).)

YCM-Gen appears to successfully generate a file for both 3.7.0 (the latest stable version) and master.
Could you please describe the failure in more detail?

**Comment by artagnon** [comment]
Unable to reproduce now. Sorry I didn't get a more detailed look at the failure; will make sure to file a better bug next time.
