### ISSUE TITLE
add compile_commands.json file to generated file too

### ISSUE THREAD

**Issue by agauniyal** [rdnetto/YCM-Generator#33]
`compilation_database_folder = ' '` 

Possible?

**Comment by rdnetto** [comment]
Sorry, could you explain your issue in a bit more detail?

**Comment by agauniyal** [comment]
When using cmake, most people write `set(CMAKE_EXPORT_COMPILE_COMMANDS ON)` in their CMakeLists.txt file and then link it as `compilation_database_folder = ' '` inside YCM's conf file. You can read this here : https://github.com/Valloric/YouCompleteMe#c-family-semantic-completion-engine-usage , 3rd paragraph.

**Comment by rdnetto** [comment]
I need to read up on this a bit, but it sounds like it shouldn't be particularly difficult to implement. Hopefully I should have time to deal with it sometime in the next week.

**Comment by autosquid** [comment]
@agauniyal  With `compilation_database_folder = ' '` set to the `compile_commands.json` , it seems extra flags set at the beginning of `.ycm_extra_conf.py` is no longer needed, AFAIK. 
In that way, it looks like a `.ycm_extra_conf.py` template is the only thing needed for a c++ project. 
Moreover, the include directories and flags will be automatically updated with a re-run of cmake which is after all necessary with a project configuration modification.

But wait, then things become familiar with `clang-complete` which I stopped to use months ago.

**Comment by phcerdan** [comment]
+1 on this.
I would be happy just with `YCM-Generator` making `YCM` aware of an in-build or temporal `.ycm_extra_conf.py` pointing to an existing in-build `compile_commands.json`. I find annoying to hand-write the path to `compile_commands.json` in an out-of-build `.ycm_extra_conf.py`. Also don't like the idea suggested in `YCM` of version controlling `compile_commands.json`, or `ycm_extra_conf.py`.
