### ISSUE TITLE
Some flags arguments are truncated

### ISSUE THREAD

**Issue by pavildon** [rdnetto/YCM-Generator#38]
For example the compilation flag 
     -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk

would be parsed and added to the ycm_extra_conf.py just as :
    -isysroot
stripping the directory location

My guess is that the generator split the string with spaces and ignore pieces that does not start with the char '-'

**Comment by rdnetto** [comment]
Resolved by #39.
