### ISSUE TITLE
link to Vim-Qt in README contains username

### ISSUE THREAD

**Issue by gauteh** [rdnetto/YCM-Generator#43]

**Comment by rdnetto** [comment]
Can you please explain what the problem is? AFAICT, that's the correct path for it.

**Comment by gauteh** [comment]
currently it is: https://rdnetto@bitbucket.org/equalsraf/vim-qt.git

if you change it to: https://bitbucket.org/equalsraf/vim-qt.git it
doesn't contain your username and firefox doesn't complain while trying
to access the page.

rdnetto writes on November 30, 2015 9:59:

**Comment by rdnetto** [comment]
Oops - must have copied & pasted the git remote. (In my defence, it looks fine when mousing over the link in Chrome.)

**Comment by gauteh** [comment]
rdnetto writes on November 30, 2015 11:00:

> Oops - must have copied & pasted the git remote. (In my defence, it looks fine when mousing over the link in Chrome.)

Just thought you might want to know :)

**Comment by rdnetto** [comment]
Oh, I did - thanks for letting me know. (You replied to my comment before I pushed the fix.)
