### ISSUE TITLE
No commands were logged to the build log?

### ISSUE THREAD

**Issue by magirldooger** [rdnetto/YCM-Generator#46]
So I had the issue and read "if you receive the error message ERROR: No commands were logged to the build logs, try using the --verbose flag to see any error messages"
So I tried :YcmGenerateConfig --verbose and tried running the config_gen.py with ./config_gen.py --verbose so how do I get more info so I can find by problem?

**Comment by rdnetto** [comment]
Could you please post the output of running with --verbose, and if possible, a link to the project you are running out against?

**Comment by magirldooger** [comment]
Where do I run --verbose with?

**Comment by rdnetto** [comment]
Like this:

```
cd my-awesome-project
~/.vim/bundle/YCM-Generator/config_gen.py --verbose .
```

Note that the exact path may vary, depending on which plugin manager you
used to install it.

**Comment by magirldooger** [comment]
So I go to my .cpp file location and run ~/.vim/bundle/YCM-Generator/config_gen.py --verbose? cause when I do I get error about how its not a command

**Comment by rdnetto** [comment]
Yes - to be more precise, you go to the root of your project, where your Makefile/etc. is. When running with `--verbose` you should see more detailed output. e.g. #40.

**Comment by magirldooger** [comment]
Sorry for not responding but is the make file some  .txt file?

**Comment by rdnetto** [comment]
The Makefile has the filename `Makefile` (or sometimes, `GNUmakefile`). There are other build systems that could be used instead, but it's impossible for me to know which without seeing the project structure. How do you normally compile it?
