### ISSUE TITLE
How to link it to YouCompleteMe version of Clang

### ISSUE THREAD

**Issue by soulslicer** [rdnetto/YCM-Generator#50]
Question above. I'd like to use YCM's build of clang but it seems only a library file is generated on their end, not an executable

**Comment by soulslicer** [comment]
I installed Clang but I  appear to be getting an error saying I don't have clang

`ERROR: Could not find clang++ at 'clang++'. Please make sure it is installed and specified appropriately.`

I do have clang++ installed and I am able to enter it into the terminal

**Comment by rdnetto** [comment]
First of all, YCM-Generator doesn't touch libclang at all - that's purely a YCM thing. Secondly, libclang actually has nothing to do with the error you're getting.

That error message is produced when YCM-Gen runs `which clang++` and it fails. Given where it's failing, it looks like it's able to find clang, but not clang++. Could you please run `which clang` and `which clang++` and let me know what their output is?

**Comment by soulslicer** [comment]
Ok, so it seems that YCM-Gen only searches for clang/clang++ ? When I installed clang, the binaries got installed at clang++-3.6. Doing a hard link solved the problem. Very strange

**Comment by pBlasiak** [comment]
Hi soulslicer,
How did you create hard link to clang++-3.6?

**Comment by pBlasiak** [comment]
I used this

sudo ln -s /usr/bin/clang-6.0 /usr/bin/clang
sudo ln -s /usr/bin/clang++-6.0 /usr/bin/clang++
