### ISSUE TITLE
support for meson build system

### ISSUE THREAD

**Issue by agauniyal** [rdnetto/YCM-Generator#51]
I'm trying out [meson](https://github.com/mesonbuild/meson) for a few pet projects and I was hoping if YCM-Generator could support it. It generates a `compile_command.json`, just like CMake does, of such format - 

```
[
  {
    "directory": "/home/agauniyal/projects/rang/build",
    "command": "ccache c++  '-pipe' '-Wall' '-Winvalid-pch' '-Wnon-virtual-dtor' '-std=c++11' '-g' '-Itest/RCBTest@exe' '-I../test' '-Itest' '-Iinclude' '-I../include' '-MMD' '-MQ' 'test/RCBTest@exe/RCBTest.cpp.o' '-MF' 'test/RCBTest@exe/RCBTest.cpp.o.d' -o 'test/RCBTest@exe/RCBTest.cpp.o' -c ../test/RCBTest.cpp",
    "file": "../test/RCBTest.cpp"
  },
  {
    "directory": "/home/agauniyal/projects/rang/build",
    "command": "ccache c++  '-pipe' '-Wall' '-Winvalid-pch' '-Wnon-virtual-dtor' '-std=c++11' '-g' '-Itest/VTest@exe' '-I../test' '-Itest' '-Iinclude' '-I../include' '-MMD' '-MQ' 'test/VTest@exe/visualTest.cpp.o' '-MF' 'test/VTest@exe/visualTest.cpp.o.d' -o 'test/VTest@exe/visualTest.cpp.o' -c ../test/visualTest.cpp",
    "file": "../test/visualTest.cpp"
  }
]
```

**Comment by rdnetto** [comment]
Unfortunately, I don't have the time available to implement support for a new build system. However, I'd be more than happy to accept a PR adding support for it.

YCM-Generator doesn't use `compile_command.json` (see #33). Instead, it works by invoking the build system with its own compiler and linker specified (usually through the `CC`, etc. environment variables). You can see the Cmake-specific logic [here](https://github.com/rdnetto/YCM-Generator/blob/develop/config_gen.py#L201).The logic is fairly straightforward, so I encourage you to try to write a patch for it if you're interested.

**Comment by vyasgiridhar** [comment]
I can take this up but not right now.
let me come back to this in a few days :)
