### ISSUE TITLE
Parameters for cmake

### ISSUE THREAD

**Issue by huiyiqun** [rdnetto/YCM-Generator#52]
I have a project built with cmake. For cross-compiling, I have to add -D to cmake, or it could not find the toolchain and wxWidget correctly.

Is it possible to add a parameter in order to append arguments when calling cmake?

**Comment by rdnetto** [comment]
Take a look at the output of `--help`:

```
  -C CONFIGURE_OPTS, --configure_opts CONFIGURE_OPTS
                        Additional flags to pass to configure/cmake/etc. e.g.
                        --configure_opts="--enable-FEATURE"
```

**Comment by huiyiqun** [comment]
Sorry, I wrongly considered it autotools-only.
