### ISSUE TITLE
Add Options for OpenFOAM build

### ISSUE THREAD

**Issue by handrake0724** [rdnetto/YCM-Generator#57]
Thanks for the nice script.
I made an option for supporting OpenFOAM in fake_build function. Could you reflect this option to the source code?
the code is as follows:

```
    elif(os.path.exists(os.path.join(project_dir, "Make/options"))):
        # OpenFOAM build
        print("Found OpenFOAM Make/options")
        print("Preparing build directory...")
        build_dir = tempfile.mkdtemp()

        keys = os.environ.keys()
        WM = re.compile('^WM_')
        for key in keys:
            if(WM.match(key)):
                env[key] = os.environ[key]

        make_args = ['wmake']
        print("\nRunning wmake...")
        proc_opts['cwd'] = project_dir
        env['WM_COMPILER']='Gcc'
        env['WM_CC']='gcc'
        # for Debug
        subprocess.call(make_args, env=env, stdin=None, stdout=None, stderr=None, shell=True, cwd=project_dir)
        #subprocess.call(make_args, env=env, **proc_opts)
```

**Comment by rdnetto** [comment]
Could you please open a PR for this? PRs make it easier to review code and preserve attribution. If you've never done so before, you can find some instructions [here](https://help.github.com/articles/using-pull-requests/). You should create the PR against the `develop` branch.

As for the code itself, could you explain why you're passing in all the `WM_` environment variables instead of just using `-e`?

Also, why are you setting `WM_COMPILER` and `WM_CC` to `gcc` instead of `clang`? And what about `WM_CXX`?

**Comment by handrake0724** [comment]
Thanks for the advice.
I just made a PR.

As for your question, 
1. OpenFOAM uses wmake (bash script used in OpenFOAM) as a build system. wmake relies on a lot of environment variables starting with WM_ as below:

> WM_LINK_LANGUAGE=c++
> WM_ARCH=linux64
> WM_OSTYPE=POSIX
> WM_THIRD_PARTY_DIR=/opt/OpenFOAM/ThirdParty-3.0.1
> WM_PROJECT_VERSION=3.0.1
> WM_CXXFLAGS=-O3
> WM_CFLAGS=-O3
> WM_COMPILER_LIB_ARCH=64
> WM_PROJECT_INST_DIR=/opt/OpenFOAM
> WM_PROJECT_DIR=/opt/OpenFOAM/OpenFOAM-3.0.1
> WM_CXX=g++
> WM_LABEL_OPTION=Int32
> WM_PROJECT=OpenFOAM
> WM_LDFLAGS=-O3
> WM_COMPILER=Gcc
> WM_MPLIB=SYSTEMOPENMPI
> WM_CC=gcc
> WM_COMPILE_OPTION=Opt
> WM_DIR=/opt/OpenFOAM/OpenFOAM-3.0.1/wmake
> WM_LABEL_SIZE=32
> WM_PROJECT_USER_DIR=/home/user/OpenFOAM/user-3.0.1
> WM_OPTIONS=linux64GccDPInt32Opt
> WM_PRECISION_OPTION=DP
> WM_ARCH_OPTION=64

   Also, since version 3.x.x, there were some changes in the environment variables. So, I just wanted to support all the OpenFOAM versions without knowing a specific version.
1. OpenFOAM supports not only gcc but also intel compiler. But, I could not compile clang with intel compiler 2013 (there might be a way, though). After several tries, I just found that temporarily settting those two variables to Gcc and gcc make config_gen.py work successfully regardless compilers.
2. Yes, you are right. setting WM_CXX to g++ may be needed (at that time, I didn't realize it cause I didn't see any problem).

**Comment by rdnetto** [comment]
Closing, as discussion is moved to PR (#58)
