### ISSUE TITLE
Do I need to manually add path?

### ISSUE THREAD

**Issue by dragonxlwang** [rdnetto/YCM-Generator#62]
This problem doesn't happen to my mac, but only to the linux server:

Using the extra conf generated, when typing "#include ...", I don't get prompted of the system library, but only those in my project folder. 

It still works okay when trying to jump to definition from c lib functions such as "strcmp"...

The server runs on scientific linux the gcc of which is old, and I use devtoolset-2 to update its gcc. so the gcc is located at `/opt/rh/devtoolset-2/root/usr/bin/gcc`. However, the header files I think are still located in `/usr/include`. If adding this path with `-I` flag to extra conf my problem solved! 

Am I supposed to do so? Or there is some other problems with my setting?

thanks!

**Comment by rdnetto** [comment]
So, YCM-Gen isn't magic, it just looks like it. :P

It relies on the build system of the project to correctly determine what flags to pass to it, given the local environment. In fact, that's all it does - it has almost no logic apart from that. So, _if_ you can compile the project on that Linux server with clang, then you either shouldn't need the flag, or the build system should be adding it automatically. (My guess is it probably doesn't compile without it.)

**Comment by dragonxlwang** [comment]
Thanks,
