### ISSUE TITLE
Special characters in directory name

### ISSUE THREAD

**Issue by Yamakaky** [rdnetto/YCM-Generator#63]
`$ pwd
/home/yamakaky/téléchargements/TP2_PARAMETRAGE/TP3 Paramétrage PVM (corrigé)
`
In vim:
`:YcmGenerateConfig
zsh:1: number expected
`
`"`, `'`, `(` are valid characters for a file name.

**Comment by rdnetto** [comment]
Looks like a big in the vimscript. Can you confirm that YCM-gen functions
correctly when invoked from the terminal?

**Comment by Yamakaky** [comment]
`~/.config/nvim/plugins/YCM-Generator/config_gen.py "$(pwd)"` gives the expected result. I think the script does something like `bin + arg`, which is incorrect. It should at least add `"`, but to give the right result in all cases it should use an argument array like `argv` in C.

**Comment by Yamakaky** [comment]
That's it: replacing `fnameescape` with `shellescape` in https://github.com/rdnetto/YCM-Generator/blob/stable/plugin/ycm-generator.vim#L17 fixes the issue.

**Comment by rdnetto** [comment]
Cool. Would you mind creating a PR for it?
