### ISSUE TITLE
YCM-Generator returns "ERROR: No commands were logged to the build log"

### ISSUE THREAD

**Issue by jeromesun14** [rdnetto/YCM-Generator#7]
Hello, I use YCM-Generator as a vim plugin, and run `:YcmGenerateConfig` in vim. But something was wrong with the following log. I ran `echo $CC` to make sure I didn't use my own environment variables.

```
Preparing build directory...
$ make clean

Running make...
$ make -i -j2
Build completed in 2.01 sec
ERROR: No commands were logged to the build log (/tmp/tmp60ki41).
Your build system may not be compatible.

Shell 已返回3

请按 ENTER 或其它命令继续
```

PS: the project I want to use YCM is the uboot source code, and I can compile it in my environment with arm-gcc. Here is my environment variables to compile it.

```
  1 #                                                                                                   
  2 # project env-setup                                                                            
  3 #                                                                                                   
  4                                                                                                     
  5 export PRJROOT=$(pwd)                                                                               
  6                                                                                                     
  7 PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin                                   
  8 #
  9 #export PATH=$PATH:${TOOLCHAIN}                                                                     
 10 export ARCH=arm                                                                                     
 11 #export CROSS=arm-cortex_a9-linux-gnueabi                                                           
 12 export CROSS=arm-linux-gnueabi                                                                      
 13 export CROSS_COMPILE=${CROSS}-                                                                      
 14 export CC=${CROSS}-gcc                                                                              
 15 export CXX=${CROSS}-g++                                                                             
 16 export LD=${CROSS}-ld                                                                               
 17 export AR=${CROSS}-ar                                                                               
 18 export NM=${CROSS}-nm                                                                               
 19 export RANLIB=${CROSS}-ranlib                                                                       
 20 export STRIP=${CROSS}-strip                                                                         
 21 export BUILD_DIR=/home/sunyongfeng/src/uboot/build
```

**Comment by rdnetto** [comment]
Try running `./config_gen.py -v $PRJROOT` in the terminal, and paste the output from that here.
The `-v` flag will display all output from the build process, which should contain whatever error is causing it to fail.

**Comment by jeromesun14** [comment]
I got "System not configured - see README" when I used `-v` flag. I used `grep -r "System not configure"` or other key word to find where this log was printed, but it outputed nothing.

Here is the log with `-v` option:

```
sunyongfeng@syf ~/.vim/bundle/YCM-Generator $ ./config_gen.py -v ~/src/uboot/
Preparing build directory...
$ make clean

Running make...
$ make -i -j2
System not configured - see README
make: [all] Error 1 (ignored)
Build completed in 0.09 sec
ERROR: No commands were logged to the build log (/tmp/tmpjFSs7K).
Your build system may not be compatible.
sunyongfeng@syf ~/.vim/bundle/YCM-Generator $ 
```

And also, there may be another issue: the default clang command is `clang-3.6`, but YCM-Generator cannot recognize it automatically, and I have to make a soft link myself to make YCM-Generator get the clang command.

```
sunyongfeng@syf ~/.vim/bundle/YCM-Generator $ ./config_gen.py -v ~/src/uboot/
ERROR: Could not find clang. Please make sure it is installed and is either in your path, or specified with --compiler.
sunyongfeng@syf ~/.vim/bundle/YCM-Generator $ 
sunyongfeng@syf ~/.vim/bundle/YCM-Generator $ sudo ln -s /usr/bin/clang-3.6 /usr/bin/clang
sunyongfeng@syf ~/.vim/bundle/YCM-Generator $ ls -al /usr/bin/clang
lrwxrwxrwx 1 root root 18  5月 10 12:41 /usr/bin/clang -> /usr/bin/clang-3.6
```

**Comment by rdnetto** [comment]
OK, that explains it. "System not configured" is an error from uboot. If I understand your first post correctly, uboot expects those variables to be defined and fails if they aren't. The solution is to use the `-e` flag, which preserves existing environment variables.

As an alternative to manually creating a symlink for clang, you can also use `-c clang-3.6`.

**Comment by jeromesun14** [comment]
There is no `-e` flag supported.

```
sunyongfeng@syf ~/.vim/bundle/YCM-Generator $ ./config_gen.py -v -e ~/src/uboot/
usage: config_gen.py [-h] [-v] [-m MAKE] [-c COMPILER] [-C CONFIGURE_OPTS]
                     [-M MAKE_FLAGS] [-o OUTPUT] [--out-of-tree]
                     PROJECT_DIR
config_gen.py: error: unrecognized arguments: -e
```

**Comment by rdnetto** [comment]
Oops, I forgot that was still on the development branch. Just merged it into stable - run git pull and try again.

**Comment by jeromesun14** [comment]
It can generate YCM configuration file now, but when I use vim, autocomplete members of  a structure failed. I will try to find out what's wrong.

Another question: `./config_gen.py -v -e ~/src/uboot/` seems to compile all the files, it's a real compile process but not the fake one as you mentioned, and that takes really too much time.

**Comment by rdnetto** [comment]
Interesting. Can you give me a link to the git repo? Uboot is big enough that it's possible they're using their own infrastructure for determining the compiler...

**Comment by jeromesun14** [comment]
Sorry, the code I used is not the original uboot, and I cannot distribute it by my own. I will try the kernel source to check if there is something wrong with my operations.

**Comment by rdnetto** [comment]
OK, that's fair enough. Let me know if you can reproduce the problem with the original, otherwise I'm not going to be able to be of much help.
