### ISSUE TITLE
Error for C only project (CMake)

### ISSUE THREAD

**Issue by 0x47** [rdnetto/YCM-Generator#88]
If I specify the language of my project (ISO C) in cmake via `project(mylib C)`, YCM-Generator fails with the following messages:

    $ ycm_generator -v -F ycm -x c .
    '/home/user/workspace/mylib/.ycm_extra_conf.py' already exists. Overwrite? [y/N] y
     Running cmake in '/tmp/tmpC0SeoR'...
    $ cmake /home/user/workspace/mylib
    -- The C compiler identification is Clang 3.8.1
    -- Check for working C compiler: /usr/share/YCM-Generator/fake-toolchain/Unix/clang
    -- Check for working C compiler: /usr/share/YCM-Generator/fake-toolchain/Unix/clang -- works
    -- Detecting C compiler ABI info
    -- Detecting C compiler ABI info - done
    -- Detecting C compile features
    -- Detecting C compile features - done
    -- Could NOT find Doxygen (missing:  DOXYGEN_EXECUTABLE) 
    -- Performing Test COMPILER_HAS_HIDDEN_VISIBILITY
    CMake Error at /usr/share/cmake-3.6/Modules/CheckCXXSourceCompiles.cmake:76 (try_compile):
      Unknown extension ".cxx" for file
    
        /tmp/tmpC0SeoR/CMakeFiles/CMakeTmp/src.cxx
    
      try_compile() works only for enabled languages.  Currently these are:
    
        C
    
      See project() command to enable other languages.
    Call Stack (most recent call first):
      /usr/share/cmake-3.6/Modules/CheckCXXCompilerFlag.cmake:50 (CHECK_CXX_SOURCE_COMPILES)
      /usr/share/cmake-3.6/Modules/GenerateExportHeader.cmake:223 (check_cxx_compiler_flag)
      /usr/share/cmake-3.6/Modules/GenerateExportHeader.cmake:377 (_test_compiler_hidden_visibility)
      CMakeLists.txt:154 (generate_export_header)
    
    
    -- Performing Test COMPILER_HAS_HIDDEN_VISIBILITY - Failed
    -- Performing Test COMPILER_HAS_HIDDEN_INLINE_VISIBILITY
    CMake Error at /usr/share/cmake-3.6/Modules/CheckCXXSourceCompiles.cmake:76 (try_compile):
      Unknown extension ".cxx" for file
    
        /tmp/tmpC0SeoR/CMakeFiles/CMakeTmp/src.cxx
    
      try_compile() works only for enabled languages.  Currently these are:
    
        C
    
      See project() command to enable other languages.
    Call Stack (most recent call first):
      /usr/share/cmake-3.6/Modules/CheckCXXCompilerFlag.cmake:50 (CHECK_CXX_SOURCE_COMPILES)
      /usr/share/cmake-3.6/Modules/GenerateExportHeader.cmake:224 (check_cxx_compiler_flag)
      /usr/share/cmake-3.6/Modules/GenerateExportHeader.cmake:377 (_test_compiler_hidden_visibility)
      CMakeLists.txt:154 (generate_export_header)
    
    
    -- Performing Test COMPILER_HAS_HIDDEN_INLINE_VISIBILITY - Failed
    -- Performing Test COMPILER_HAS_DEPRECATED_ATTR
    CMake Error at /usr/share/cmake-3.6/Modules/CheckCXXSourceCompiles.cmake:76 (try_compile):
      Unknown extension ".cxx" for file
    
        /tmp/tmpC0SeoR/CMakeFiles/CMakeTmp/src.cxx
    
      try_compile() works only for enabled languages.  Currently these are:
    
        C
    
      See project() command to enable other languages.
    Call Stack (most recent call first):
      /usr/share/cmake-3.6/Modules/GenerateExportHeader.cmake:199 (check_cxx_source_compiles)
      /usr/share/cmake-3.6/Modules/GenerateExportHeader.cmake:245 (_check_cxx_compiler_attribute)
      /usr/share/cmake-3.6/Modules/GenerateExportHeader.cmake:378 (_test_compiler_has_deprecated)
      CMakeLists.txt:154 (generate_export_header)
    
    
    -- Performing Test COMPILER_HAS_DEPRECATED_ATTR - Failed
    -- Performing Test COMPILER_HAS_DEPRECATED
    CMake Error at /usr/share/cmake-3.6/Modules/CheckCXXSourceCompiles.cmake:76 (try_compile):
      Unknown extension ".cxx" for file
    
        /tmp/tmpC0SeoR/CMakeFiles/CMakeTmp/src.cxx
    
      try_compile() works only for enabled languages.  Currently these are:
    
        C
    
      See project() command to enable other languages.
    Call Stack (most recent call first):
      /usr/share/cmake-3.6/Modules/GenerateExportHeader.cmake:199 (check_cxx_source_compiles)
      /usr/share/cmake-3.6/Modules/GenerateExportHeader.cmake:251 (_check_cxx_compiler_attribute)
      /usr/share/cmake-3.6/Modules/GenerateExportHeader.cmake:378 (_test_compiler_has_deprecated)
      CMakeLists.txt:154 (generate_export_header)
    
    
    -- Performing Test COMPILER_HAS_DEPRECATED - Failed
    -- Configuring incomplete, errors occurred!
    See also "/tmp/tmpC0SeoR/CMakeFiles/CMakeOutput.log".
    See also "/tmp/tmpC0SeoR/CMakeFiles/CMakeError.log".
    
    Running make...
    $ make -i -j8
    make: *** No targets specified and no makefile found.  Stop.
    
    Cleaning up...
    
    Build completed in 0.51 sec
    
    Collected 0 relevant entries for C compilation (0 discarded).
    Collected 0 relevant entries for C++ compilation (0 discarded).
    
    ERROR: No commands were logged to the build logs (C: /tmp/tmpDpDbPN, C++: /tmp/tmplqwrQA).
    Your build system may not be compatible.

**Comment by rdnetto** [comment]
How do you compile the project normally?

**Comment by 0x47** [comment]
It appears this is an issue of CMake, not of YCM-Generator (see their [#15829](https://gitlab.kitware.com/cmake/cmake/issues/15829)). I had problems identifying this issue as such because this only happens once. After that, an empty/broken header file is generated and the error does not appear again. This made it look like the build was working for my build tree and not for the (fresh) YCM-Completer build tree. Sorry for the confusion.
