### ISSUE TITLE
Automatically detect 'compile_commands.json' for CMake projects.

### ISSUE THREAD

**Issue by foreverbell** [rdnetto/YCM-Generator#92]
Can we automatically set `compilation_database_folder` in `template.py` if we see `compile_commands.json` exists for a `cmake` project?

It is trivial to add it and I can't see any downside of adding it. Can we add this feature?

Thanks.

**Comment by rdnetto** [comment]
I have no problem with it being added, but I don't have enough time to do right now. PRs are welcome. ;)
